### ISSUE TITLE
Add Contact Model function.

### ISSUE THREAD

**Issue by Kodamayuto2001** [Kodamayuto2001/springMVC#1]
### ToDo

- [x] Creating a table
- [x] Creating a 'Contact Data Class'
- [x] Creating a 'Contact Interface Class'
- [x] Creating a 'ContactDAOImpl Class'
- [x] Creating a 'ContactDAOTest Class'
- [x] #13

![image](https://user-images.githubusercontent.com/55943803/153702704-3d07895e-bdef-40fc-9e2b-1ece8c1b15e8.png)
